*******************************************************************************
*
*       Program COMMONVAR.H
*       
*       Copyright (C) 2021
*
*
*******************************************************************************
*
*  Author: rprasad
*  Created on: Jul 20, 2021 11:03:36 PM
*  Description:
*
*
*****************************************************************************
* COMMON VARIABLE
COMMON OS.TYPE, OS.SEP, UDACCOUNT, UDHOME, LOGGING, LogFilePath, LogFile

* CONSTANT defination
EQUATE	TRUE	TO	1
EQUATE	FALSE	TO	0

* ERROR number defination
EQUATE  SUCCESS     TO  999 ;* Math operation success
EQUATE	ADDERR	    TO	100	;* Invalid Addition
EQUATE	SUBERR      TO	200	;* Invalid Substraction
EQUATE	MULERR	    TO	300	;* Invalid Multiplication
EQUATE	DIVERR	    TO	400	;* Invalud Division


